### PR TITLE
Update site for 2022 event

### PR DESCRIPTION
**Pull request by avdata99**
This PR:
 - Update site to 2022
 - A test application was added and works
 - Schema updated (many fields were removed)
 - local `/etl/2022.py` run without errors
 - static content build works locally

Pending:
 - Do we need a link to the 2022 form? It seem we don't have a link for the 2021 edition
 - I can't properly show the OKFN svg logo.

image

image

image

image

image

### CODE REVIEW

**Review by aivuk — APPROVED** [review]
Looks good to me, I tried locally and the only update that I did need to do was in the counter over the map at `content/contents.lr`. The link to register an event using google forms is still the 2021 one.

**Comment by StephenAbbott** [comment]
@avdata99 Hi Andres. I helped run Open Data Day last year. The 2021 form is [here](https://docs.google.com/forms/d/e/1FAIpQLSfBBp5CZXe2M8wXulTNgRTZWo1PD2raB6IEEha9FJaq6hVSfQ/viewform) and is linked to from the blue 'Register your event' button. This Google form can obviously be easily copied/adapted. I left a bunch of handover notes for stuff like this in case that helps

**Comment by avdata99** [comment]
>

**Comment by avdata99** [comment]
> @avdata99 Hi Andres. I helped run Open Data Day last year. The 2021 form is [here](https://docs.google.com/forms/d/e/1FAIpQLSfBBp5CZXe2M8wXulTNgRTZWo1PD2raB6IEEha9FJaq6hVSfQ/viewform) and is linked to from the blue 'Register your event' button. This Google form can obviously be easily copied/adapted. I left a bunch of handover notes for stuff like this in case that helps

Thanks @StephenAbbott. The OKF team already created a new form (based on last one) and I just found how to link with this site.
If you find something to improve in this PR, I will be grateful if you share it with me.

**Pull request merged**
