### PR TITLE
Move register_text from map to resources.

### PR DESCRIPTION
**Pull request by openbrian**

### CODE REVIEW

**Comment by morchickit** [comment]
Why? I don't understand the UX logic

**Comment by openbrian** [comment]
For my event, we're meeting online in Slack, in in person.  There's no single location per see on the map.  As a user, I don't think I need to go to the map in order to add an event.

On the other hand, for someone who is registering an event the resources are useful.  Perhaps an even better location is in the header, but that's up to you.

**Comment by openbrian** [comment]
For my event, we're meeting online in Slack, not in person. There's no single location per see on the map. As a user, I don't think I need to go to the map in order to add an event.

On the other hand, for someone who is registering an event the resources are useful. Perhaps an even better location is in the header, but that's up to you.
Brian
http://derocher.org/~brian
http://mappingdc.org

**Comment by morchickit** [comment]
While I understand the user story (As an event organizer of a virtual event I want to list my event not on a map so others can participate), this is a one case scenario, and most events are local. I am closing this pull request for two reasons:
1. The resource page is a separate page, and it's not intuitive to find event registration there.
2. Most events are local, and the map helps to reflect it. 

We used to have a wiki, but many people didn't use it, so we deleted it, but we should think how to accomodate it. 
We should open a user story to reflect your need, and to find a solution, but I am not sure your solution here is the right one.

**Pull request closed without merging**
