### PR TITLE
Removed de_at from lektorproject

### PR DESCRIPTION
**Pull request by loleg**
Corrects the build blocking issue #257 to complete #256 

Local build works fine.

### CODE REVIEW

**Comment by loleg** [comment]
@StephenAbbott this seems to have been reverted. Any idea why?

**Comment by chris48s** [comment]
I suspect this got reverted because only removing the item from lektorproject but leaving in the list of languages ( https://github.com/okfn/opendataday/blob/master/databags/languages.json ) probably left us with a broken link in the menu and reverting this "fixed" it.

@StephenAbbott - can you confirm we're good to remove this and I'll clean out all the de_at content (I'm doing some work on the site at the moment anyway)

**Comment by StephenAbbott** [comment]
Thanks @chris48s. From memory, I think you're right. Happy for you to do the necessary to remove the de_at translation

**Comment by StephenAbbott** [comment]
And thanks @loleg for flagging

**Comment by chris48s** [comment]
Fully removed in https://github.com/okfn/opendataday/commit/f93e30b65c346288cf5b39b0756b9cb8b0f75754

**Comment by loleg** [comment]
Thanks both!

**Pull request merged**
