### PR TITLE
Translation into Korean

### PR DESCRIPTION
**Pull request by givemetarte**
# Overview

Hi, there. 
Those requests are what I've done for translation into Korean. 

---

Please preserve this line to notify @StephenAbbott

### CODE REVIEW

**Comment by givemetarte** [comment]
Hi, @StephenAbbott 
Could you check this error?

**Comment by StephenAbbott** [comment]
Thanks for this work. Looking at solving the issues now, @givemetarte

**Comment by chris48s** [comment]
Hi. Going to close this PR but I [cherry-picked your commits](https://github.com/okfn/opendataday/commits?author=givemetarte)  and fixed the build. Korean translation is now live at https://opendataday.org/kr/ :tada: 
Thanks for your contribution.

**Comment by StephenAbbott** [comment]
Thanks @chris48s

**Pull request closed without merging**
