### PR TITLE
update pt-br translation to 2021

### PR DESCRIPTION
**Pull request by augusto-herrmann**
Updated taking into account the change history of commits to the English file `contents.lr`.

### CODE REVIEW

**Comment by augusto-herrmann** [comment]
Could we please get this merged, @roll ?

I would like to start sharing the date for ODD 2021 in Brazilian groups and it would be great if the site was up to date in Portuguese.

**Comment by roll** [comment]
Hi @augusto-herrmann,

@StephenAbbott leads this repo work. Pinging him but I guess it's OK if I merge if there is no answer today

**Comment by StephenAbbott** [comment]
Thanks for the translaation @augusto-herrmann and for merging, @roll

**Comment by augusto-herrmann** [comment]
Thanks, @StephenAbbott and @roll !

**Pull request merged**
